vimeo/VimeoNetworking

- VimeoNetworking.podspec
No issue associated with this one. 
Just ensuring that the plist isn't captured as part of the pod's "source".
> Updated source definition to ensure plist is not captured as source.

- VimeoNetworking/VimeoNetworking.xcodeproj/project.pbxproj
- VimeoNetworking/VimeoNetworking/AuthenticationController.swift
- VimeoNetworking/VimeoNetworking/VimeoNetworking.h
[CAM-265](https://vimean.atlassian.net/browse/CAM-265)
I'm building out a revised user system for the Cameo-iOS app. As part of this, we're leveraging the VimeoNetworking accounts system. Because of differences with how the Cameo-iOS app treats users, we don't want to call `loadSavedAccount`, but prefer to be able to be more explicit by calling a method like `loadUserAccount` or `loadClientCredentialsAccount`. 
I made the above changes. Introducing these two new methods. Modifying existing logic to leverage these two new methods. And marked `loadSavedAccount` as deprecated because it sounds like we're moving to a more specific API, away from the general-ness of `loadSavedAccount` (because it attempts to load a user account, and if it can't it then attempts to load a client credentials …
> CAM-265: Modified loadSavedAccount logic

- VimeoNetworking/VimeoNetworking.xcodeproj/project.pbxproj
- VimeoNetworking/VimeoNetworking/NSURLSessionConfiguration+Extensions.swift
- VimeoNetworking/VimeoNetworking/VimeoSessionManager+Constructors.swift
N/A
The VimeoSessionManager is using the default NSURLSessionConfiguration which has a request cache policy of .UseProtocolCachePolicy.  This is causing certain API calls (ex. /me/videos) to return back cached data instead of fetching new results from the server, which is resulting in the wrong data being returned when logging in with different user accounts. 
I created some convenience methods in an extension of the NSURLSessionConfiguration class.  These methods allow you to create a new default session configuration by passing in the desired caching policy.  I modified the code in VimeoSessionManager+Constructors to use the new convenience methods to create default session configurations that have cache policies set to .ReloadIgnoringCacheData, which will disable the URL cache.
1) Log …
> cam-xxx-disable-request-cache

- VimeoNetworking/VimeoNetworking/ErrorCode.swift
[CAM-211](https://vimean.atlassian.net/browse/CAM-211)
This ticket is about cancelling all uploads within Cameo-iOS when the user logs out. And the task requires checking if a network failure (video deletion) failed due to a 404. In the case of video deletion this isn't actually a failure, it's just a validation that the video we wanted to delete has already been deleted 👍. 
A good ol' one liner. 
Aint no test unless you build Cameo, but that'll be tested as part of the Cameo-iOS PR.
> CAM-211: Added a new value (404 NotFound) HTTPStatusCode enum

- VimeoNetworking/VimeoNetworking/NSError+Extensions.swift
[CAM-208](https://vimean.atlassian.net/browse/CAM-208)
Add upload analytics to Cameo that mirror the ones we have in Vimeo iOS
In order to bring some of the Vimeo analytics code into Cameo I need to add some convenience methods to the NSError extension that were previously defined in VIMNetworking.
N/A
> CAM-208: adding convenience methods to NSError extension

- VimeoNetworking/VimeoNetworking.xcodeproj/project.pbxproj
- VimeoNetworking/VimeoNetworking/Models/VIMThumbnailUploadTicket.h
- VimeoNetworking/VimeoNetworking/Models/VIMThumbnailUploadTicket.m
[CAM-308](https://vimean.atlassian.net/browse/CAM-308)
We need a new upload descriptor for Cameo that encapsulates the whole upload process, including uploading custom thumbnail images.
I'm adding a new model object that will store the information needed to upload a thumbnail image.
N/A
> CAM-308: Adding a new model for tracking thumbnail upload information

- VimeoNetworking/VimeoNetworking.xcodeproj/project.pbxproj
- VimeoNetworking/VimeoNetworking/NSError+Extensions.swift
- VimeoNetworking/VimeoNetworkingTests/NSErrorExtensionTests.swift
N/A
Fixed a bug in the NSError extension parsing logic for the invalid_parameters array returned in the error JSON object.
In the vimeoInvalidParametersErrorCodes property we were incorrectly casting the value of the "error_code" field to a String and then attempting to cast it to an Int before adding it to the returned array.  The value was already an Int in the JSON data, so the cast to string was failing which caused us to always return an empty array.  I fixed the logic to remove the incorrect String cast.  I also added a set of unit tests to make sure all of the properties in the extension are returning the correct values.  This commit also includes a new convenience property to get the VimeoUserMessage from the invalid parameters error JSON object.
1. Run the unit tests.
> CAM-XXX: Fixed a bug in the NSError extension parsing logic

- VimeoNetworking/VimeoNetworking/Mappable.swift
This fixes an issue where we couldn't cast an Array response to an expected array of model objects correctly.  By adding the associated type, it allows us to restrict the generic parameters in a function or class as such: `<ModelType: MappableResponse where ModelType.Element: VIMModelObject>`.  This merely makes explicit what we already know, that we're only requesting model objects from the api, and it also fixes our ability to make that cast: `let newItems = response.model as? [ModelType.Element]`
> Adding associatedtype Element to MappableResponse 

- VimeoNetworking/VimeoNetworking/Request+Cache.swift
- VimeoNetworking/VimeoNetworking/ResponseCache.swift
- VimeoNetworking/VimeoNetworking/VimeoClient.swift
[https://vimean.atlassian.net/browse/TVOS-228](https://vimean.atlassian.net/browse/TVOS-228)
Implement a Streams view controller that can present and scroll sections as rows individually
**see Vimeo-tvOS PR for context on the user-facing feature** 
Modified two things relating to caching:
* cache keys now all start with "cached" (for aesthetics really) and they omit the "fields" parameter because it was making our filenames too long
* `ResponseCache` no longer generates an actual `Response` object from the response dictionary.  It instead passes control of this dictionary back to `VimeoClient` for parsing into the final `Response` object.  This is to allow the parsing of pagination parameters to stay contained in `VimeoClient`, but it's also nice to consolidate this architecturally.
> TVOS-228: Row Streams View Controller on tvOS

- VimeoNetworking/VimeoNetworking/Request.swift
[TVOS-85](https://vimean.atlassian.net/browse/TVOS-85)
[TVOS-81](https://vimean.atlassian.net/browse/TVOS-81)
* Tweaked the ways next page `Request`s are generated and accessed for more consistency.
* When you init a `Request` with a `path`, it will now strip any query string parameters correctly and put them in the parameters and pagination variables as appropriate.
* You can now get a `Request.URI`, which is the path plus a query string of any parameters. This simplifies stream next page requests.
> TVOS-85: Feed Stream

- VimeoNetworking/VimeoNetworking/VimeoClient.swift
Incorrectly assumed that AFNetworking returned us to a background queue in their completion blocks, but they actually default to the main queue, so all our model object parsing and whatnot was being done there 😱
> Dispatch VimeoClient task success/failure to a background queue for parsing

- VimeoNetworking/VimeoNetworking/VimeoResponseSerializer.swift
[TVOS-353](https://vimean.atlassian.net/browse/TVOS-353)
[TVOS-355](https://vimean.atlassian.net/browse/TVOS-355)
- DEV | Build a cell for VOD items
- Build a collection view cell for VIMVODItem display on tvOS.
- This includes a VOD icon in the top left and a Trailer/"X days left" small VODItemStatusView in the top right.  It also includes an "N videos" label in place of what would be the duration label on a VideoCell.
- DEV | Add purchases stream to Library page
- This should be a relatively straightforward addition to our Library page, we should already have a stream for our VOD library that returns objects of type VIMVODItem
- added the VOD item content type to the accepted JSON types header
Log into various VOD test accounts, listed here: …
> TVOS-353/5: VOD Item Cell and Purchases List

- VimeoNetworking/VimeoNetworking/Models/VIMBadge.swift
- VimeoNetworking/VimeoNetworking/Models/VIMVideo.h
- VimeoNetworking/VimeoNetworking/Models/VIMVideo.m
- VimeoNetworking/VimeoNetworking/VimeoResponseSerializer.swift
[TVOS-354](https://vimean.atlassian.net/browse/TVOS-354)
Add VOD flourishes to our existing VideoCell, for VOD videos appearing everywhere else in the app but the Purchases list. This includes a VOD icon in the top left and a Trailer/"X days left" small VODItemStatusView in the top right.
- Added VIMBadge for API returned badges
- Added badge field to video
> TVOS-354: Adding VIMBadge to video objects

- VimeoNetworking/VimeoNetworking/Models/VIMVideo.m
NA
The iOS project does not support `VimeoNetworking` as a Cocoapod yet, but this is forthcoming. The TVOS project does, and needs to import this header file to make a new model written in swift visible to `VIMVideo` written in Objective-C. 
Wrap import in macro to check OS.
See parent PR.
> Resolve compatibility issues with iOS project

- VimeoNetworking/VimeoNetworking.xcodeproj/project.pbxproj
- VimeoNetworking/VimeoNetworking/Models/VIMConnection.h
- VimeoNetworking/VimeoNetworking/Models/VIMConnection.m
- VimeoNetworking/VimeoNetworking/Models/VIMProgrammedContent.swift
- VimeoNetworking/VimeoNetworking/Models/VIMVideoProgressiveFile.h
- VimeoNetworking/VimeoNetworking/Request+ProgrammedContent.swift
- VimeoNetworking/VimeoNetworking/VimeoResponseSerializer.swift
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/project.pbxproj
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/FakeDataSource.swift
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/ModelObjectValidationTests.swift
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/programmed_cinema.json
[TVOS-373](https://vimean.atlassian.net/browse/TVOS-373)
Add new model object to represent ProgrammedContent objects returned from the new /programmed/* endpoints.  Add a new request for fetching objects from the new /programmed/cinema endpoint.
- Added VIMProgrammedContent model object
- Added a new VIMConnection for ProgrammedContents "contents" connection.
- Added Request+ProgrammedContent extension and added method for creating Cinema requests
- Added the FakeDataSource class to help with writing unit tests to check model parsing logic.  The FakeDataSource class allows you to read in a JSON file that can be created by saving the output of a curl request against an API endpoint.  The class then parses the model objects out of the JSON file using the same object mapper that's used by …
> TVOS-373: Add model object for Programmed Content endpoint

- Podfile.lock
- VimeoNetworking/VimeoNetworking/AuthenticationController.swift
- VimeoNetworking/VimeoNetworking/Request+Authentication.swift
- VimeoNetworking/VimeoNetworking/Request+Cache.swift
- VimeoNetworking/VimeoNetworking/Request+Channel.swift
- VimeoNetworking/VimeoNetworking/Request+Configs.swift
- VimeoNetworking/VimeoNetworking/Request+Trigger.swift
- VimeoNetworking/VimeoNetworking/Request+User.swift
- VimeoNetworking/VimeoNetworking/Request+Video.swift
- VimeoNetworking/VimeoNetworking/Request.swift
- VimeoNetworking/VimeoNetworking/ResponseCache.swift
- VimeoNetworking/VimeoNetworking/String+Parameters.swift
- VimeoNetworking/VimeoNetworking/VimeoClient.swift
https://vimean.atlassian.net/browse/VIM-4736
Previously, VimeoNetworking only supported dictionary types for request parameters. We need to support array types as well as required by certain requests to out API.
- Modified the `parameters` of Request to be of type AnyObject (corresponding to the AFNetworking and Apple APIs)
- Cleaned up some cache code
- Moved some request code from the app to VimeoNetworking
Make sure networking works as expected.
> VIM-4736: AnyObject Parameters

- VimeoNetworking/VimeoNetworking/Models/VIMPolicyDocument.h
- VimeoNetworking/VimeoNetworking/Models/VIMPolicyDocument.m
- VimeoNetworking/VimeoNetworking/Request+PolicyDocument.swift
- VimeoNetworking/VimeoNetworking/VimeoNetworking.h
- VimeoNetworking/VimeoNetworking/VimeoResponseSerializer.swift
[TVOS-433](https://vimean.atlassian.net/browse/TVOS-433)
[TVOS-434](https://vimean.atlassian.net/browse/TVOS-434)
Added a new model and request for retrieving policy documents from the API endpoint.
- VIMPolicyDocument - model to represent document object returned from the API
- Request+PolicyDocument - extension to the Request class that adds convenience methods for creating document requests.
N/A
> Add model and requests for PolicyDocuments.

- VimeoNetworking/VimeoNetworking/VimeoRequestSerializer.swift
https://vimean.atlassian.net/browse/VIM-4739
Make VimeoRequestSerializer a AFJSONRequestSerializer.
After going back and forth with the API, we fixed all the issues surrounding authentication and JSON request serializers. Now that this is fixed we can make JSON requests.
Resolved API issues:
https://github.vimeows.com/Vimeo-API/api/issues/679
https://github.vimeows.com/Vimeo-API/api/issues/727
Make sure everything works as expected, especially auth.
> VIM-4739: JSON Request Serializer

- VimeoNetworking/VimeoNetworking/AccountStore.swift
- VimeoNetworking/VimeoNetworking/AppConfiguration.swift
- VimeoNetworking/VimeoNetworking/KeychainStore.swift
https://vimean.atlassian.net/browse/VIM-4790
VimeoNetworking was previously using a different keychain configuration to store accounts than VIMNetworking. This PR reverts that change. This allows for seamless migrations from VIMNetworking to VimeoNetworking.
Modified the keychain keys. Also removed the default keychain values from AppConfiguration.
Logged in, migrate from 6.1.3 to 6.1.4. You should remain logged in.
> VIM-4790: Keychain Fix

- VimeoNetworking/Sources/Notification.swift
- VimeoNetworking/Sources/VimeoClient.swift
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/project.pbxproj
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/NSErrorExtensionTests.swift
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VimeoClientTests.swift
[VIM-4833](https://vimean.atlassian.net/browse/VIM-4823)
Downloads disappear after upgrading from 6.1.3 to 6.1.5 when logged out
Added ability to pass userInfo dictionary when posting notifications so that I can inspect previous user accounts when account changes.
Unit test in VimeoClientTests.swift
> VIM-4833: Add support for passing userInfo when posting Notifications

- VimeoNetworking/Sources/ResponseCache.swift
- circle.yml
https://vimean.atlassian.net/browse/VIM-4132
Cached files aren't removed when logged out.
Added a sub directory to /Library/Caches folder so that when we call:
`removeAllResponseDictionaries` in `ResponseCache` file, we actually have the permissions to delete the files of this folder.
We used to try to remove the Caches folder that Apple has generated, but we don't have the permissions to remove it.
So we got this issue:
```Error Domain=NSCocoaErrorDomain Code=513 "“Caches” couldn’t be removed because you don’t have permission to access it." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/F307995B-BD12-45BB-AA61-6188CBC6F635/Library/Caches, NSUserStringVariant=(
Remove
), NSUnderlyingError=0x113e4adf0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
```
1. …
> VIM-4132: Response Cache

- VimeoNetworking/Sources/Models/VIMVideoPreference.h
- VimeoNetworking/Sources/Models/VIMVideoPreference.m
https://vimean.atlassian.net/browse/VIM-4879
Crash on uploading a Video.
Updated the model `VIMVideoPreference` so that the property `privacy` instead of being a type `String`, it should be a `VIMPrivacy` object.
1. Open app
2. Log in 
3. Tap Upload
4. Select video
5. Upload should work.
> VIM-4879: Fixed crash on accessing `Privacy` property.

- VimeoNetworking/Sources/Request.swift
https://vimean.atlassian.net/browse/AF-3
https://vimean.atlassian.net/browse/VIM-4809
https://vimean.atlassian.net/browse/AF-5
Default the caching policy back to what we used to have in VIMNetworking.
Updated caching policy to .NetworkOnly.
2 things to check:
A)
1. Tap on Explore 
2. Tap on any category 
3. Tap on a subcategory 
4. Tap on back 
5. Tap on a the same subcategory again
6. Subcategory should be open only once.
B)
Check that in VIMNetworking, it was NetworkOnly: 
https://github.com/vimeo/VIMNetworking/blob/v6.1.2/VIMNetworking/Networking/VimeoClient/VIMRequestDescriptor.m
```
- (instancetype)init
{
self = [super init];
if (self)
{
self.descriptorID = @"";
self.urlPath = @"";
self.HTTPMethod = HTTPMethodGET;
self.parameters = nil;
self.cachePolicy = VIMCachePolicy_NetworkOnly; …
```
> AF-3: Updated `caching policy`

- VimeoNetworking/Sources/ErrorCode.swift
[VIM-4897](https://vimean.atlassian.net/browse/VIM-4897)
Related to this [PR](https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/1189)
The app did not show the alert when an unverified user attempted to post a comment because:
a) There was neither title nor message for that error
b) The code for the error was not specified in the enum
I added the error code into the enum as well as the texts for the alert.
1. Create an account and don't verify it.
2. Attempt to post a comment or a reply. You'll see the alert appearing.
> Add Unverified User Error

- VimeoNetworking/Sources/Models/VIMVideoPreference.m
https://vimean.atlassian.net/browse/VIM-4918
Write a migration to upgrade the old version of privacy (a string) to the new version (an object).
Added the migration to create a new privacy object and set the string in the correct place. Jennifer already updated the model and code in another PR: https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/1177
- Log out
- Download the app store version
- Log in
- Upgrade
- Go to upload a video
The app should no longer crash at this point.
> VIM-4918: Default Privacy Migration

- .github/PULL_REQUEST_TEMPLATE.md
[VIM-4977](https://vimean.atlassian.net/browse/VIM-4977)
(1) Update the PR template to facilitate more helpful PR descriptions from developers. 
(2) Add a PR checklist for the contributor to fill in prior to requesting PR review
Pain points this is trying to solve
- We'd like to identify some expectations we have for devs who don't contribute to our repos regularly by listing them in a PR checklist 
- Sometimes we copy and paste the ticket description (if applicable) inside _Issue Summary_. Instead let's translate the ticket / general issue into the technical problem we're trying to solve so we're not trying to figure this out while reading about implementation. 
- instead of: "Build the new 'foo feature' page", do "(1) Implement a new collection view with cells that  are populated by the …
> VIM-4977: JAM - Updated PR template proposal

- VimeoNetworking/Sources/Models/VIMVideo+SVOD.h
- VimeoNetworking/Sources/Models/VIMVideo+SVOD.m
N/A
- We didn't return an invalid type for SVODAccess if the video isn't SVOD.
- Created a new type Invalid for svodAccess. That way if a video isn't svod and we try to access it, it will return an invalid type.
N/A
> Updated VIMVideo SVOD Extension

- Pods/Pods.xcodeproj/project.pbxproj
- Pods/Target Support Files/VimeoNetworking-iOS/VimeoNetworking-iOS-umbrella.h
- Pods/Target Support Files/VimeoNetworking-tvOS/VimeoNetworking-tvOS-umbrella.h
- VimeoNetworking/Sources/Request+Purchasing.swift
- VimeoNetworking/Sources/Response.swift
- VimeoNetworking/Sources/Scope.swift
- VimeoNetworking/Sources/VimeoClient.swift
[AF-28](https://vimean.atlassian.net/browse/AF-28)
[TVOS-719](https://vimean.atlassian.net/browse/TVOS-719)
- This PR adds a new extension to the Request structure for generating purchase requests to unlock IAP items.  It also adds a new scope for granting purchasing permissions to the app.  A couple of things were made public, which was necessary in order to create mock objects in the client apps for testing purposes.
- Request+Purchasing - The new Request extension.  It creates a new request for unlocking purchased items by taking in a uri for the product to unlock and the Apple app store receipt for validation.
- Scope - added a new scope for "purchase"
- Response - made the initializer public so we can create Response objects in mock / testing code.
- VimeoClient - made RequestToken …
> AF-28: Add new request for SVOD purchasing

- VimeoNetworking/Sources/Models/Subscription.swift
- VimeoNetworking/Sources/Models/VIMUser.h
- VimeoNetworking/Sources/Models/VIMUser.m
[VIM-4861](https://vimean.atlassian.net/browse/VIM-4861)
Added a helper method that will be used to determine whether we should enable all the notifications settings.
The `Subscription model` has been updated:
A helper has been added to determine if the user has all the settings for push notifications disabled.
N/A
N/A
> VIM-4861: Notifications cleanup

- circle.yml
This PR disable pod caching which puts the build environment in an undetermined state since Pods are checked into the repo.
> CI-439 Disable pod cache

- VimeoNetworking/Sources/AuthenticationController.swift
- VimeoNetworking/Sources/VimeoClient.swift
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS/AppDelegate.swift
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS/MasterViewController.swift
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS/VimeoClient+Shared.swift
[CRI-108](https://vimean.atlassian.net/browse/CRI-108)
Since internal frameworks rely on a previously extracted singleton instance, we needed to add a way for clients to configure the singleton instance
- Made AppConfiguration and VimeoSessionManager on VimeoClient optional
- Add static methods for singleton and singleton configuration
> [CRI-108] Singleton for VimeoClient

- VimeoNetworking/Sources/Models/VIMModelObject.m
N/A
- We were formerly creating a new date formatter for each use, which is very expensive. This PR changes this date formatter to be a singleton.
- Wrapped existing date formatter in a singleton pattern to ensure only one instance is created.
N/A
> AF-XXX: Make Date Formatter in Object Mapper a Singleton

- codecov.yml
N/A
- Change the default branch to develop in the codecov dashboard.
- codecov.yml - added a yaml file to configure the default branch.
> AF-XXX: set the default branch to develop for the codecov dashboard

- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VimeoSessionManagerTests.swift
N/A
- Added two new unit tests to check functionality of VimeoSessionManager account handling methods.
- VimeoSessionManagerTests - added a unit test to verify that the session manager properly sets the accessTokenProvider on the request serializer from a VIMAccount and a test that verifies it's properly removed.
- Run the unit tests
> AF-XXX: Added more unit tests for VimeoSessionManager

- VimeoNetworking/Sources/VimeoRequestSerializer.swift
N/A
We were hitting an assert on tvOS when constructing the user agent on requests.
AFNetworking doesn't set a User Agent for tvOS. This was tripping the `assertionFailure`. See the comment in the code for more deetz.
Make sure request construction works on tvOS.
> VIM-XXX: tvOS User Agent Fix

- VimeoNetworking/Sources/AuthenticationController.swift
- VimeoNetworking/Sources/Request+Authentication.swift
[VIM-5494](https://vimean.atlassian.net/browse/VIM-5494)
- We needed to add 2 new requests to our backend in order to login or join using a third party derived token. Instead of adding them here, where they won't be usable by non-Vimeo consumers, some api was made public so that clients consuming VimeoNetworking can more easily do that within their project. 
- made `authenticateWithRequest` publicly accessible
- made typealias `AuthenticationRequest` publicly accessible
- N/A
> VIM-5494: Authenticate with Vimeo Backend

- Pods/Pods.xcodeproj/project.pbxproj
- VimeoNetworking/Sources/Models/VIMLive.swift
- VimeoNetworking/Sources/Models/VIMVideo.h
- VimeoNetworking/Sources/Models/VIMVideo.m
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/project.pbxproj
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VIMLiveTests.swift
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/clip_live.json
[VIM-5562](https://vimean.atlassian.net/browse/VIM-5562)
The goal of this PR is to update the `VIMVideo` class so that it has additional fields for live streaming.
- Introduce a new model class `VIMLive` whose structure reflects the following response:
```
"live": {
"link": "rtmp://rtmp.cloud.vimeo.com/live?token=b23a326b-eb96-432d-97d5-122afa3a4e47",
"key": "42f9947e-6bb6-4119-bc37-8ee9d49c8567",
"active_time": "2017-08-01T18:18:44+00:00",
"ended_time": null,
"archived_time": null,
"status": "streaming"
}
```
- Add a new `VIMLive` property to the `VIMVideo` class.
- In the implementation of `VIMVideo`, register the `VIMLive` type to be recognized by the object mapper.
- Add a unit test to check if parsing the live object is correct.
- Make sure all unit tests pass.
N/A
> VIM-5562: Add New `Live` Properties to `VIMVideo` Class

- VimeoNetworking/Sources/Models/VIMVideo.h
- VimeoNetworking/Sources/Models/VIMVideo.m
- VimeoNetworkingExample-iOS/VimeoNetworkingCommonTests/VIMVideoTests.swift
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/project.pbxproj
[VIM-5610](https://vimean.atlassian.net/browse/VIM-5610)
Create an easy way to determine whether or not a VIMVideo object has a live video associated with it.
Added a new `isLive` convenience method to look for the existence of a VIMLive object. This was to match the existing behavior for `is360`. Also added a couple tests to verify that the new method worked as expected. 
- Build and run unit tests.
> VIM-5610: Adds a convenience method to check if live object exists

- VimeoNetworking/Sources/Models/VIMLive.swift
- VimeoNetworking/Sources/Models/VIMVideo.h
- VimeoNetworking/Sources/Models/VIMVideo.m
[VIM-5585](https://vimean.atlassian.net/browse/VIM-5585)
- Added constants to VIMLive to mirror the status enum, because the enum is not available via Objective-C.
- Added convenience methods to return whether or not a live video is pre, mid, or post broadcast.
> VIM-5585: Update VIMLive and VIMVideo

- VimeoNetworking/Sources/Models/VIMLive.swift
- VimeoNetworking/Sources/Models/VIMVideo.h
- VimeoNetworking/Sources/Models/VIMVideo.m
[VIM-5658](https://vimean.atlassian.net/browse/VIM-5658)
Update VIMVideo and VIMLive object to handle changes from Vimeo API version 3.3.13.
- Added the `archiving` status to **VIMLive**.
- Added the `unavailable` status to the dictionary of valid video statuses for **VIMVideo**.
> VIM-5658: Update VIMVideo and VIMLive for API version 3.3.13

- VimeoNetworking/Sources/Models/VIMVideo.h
- VimeoNetworking/Sources/Models/VIMVideo.m
- VimeoNetworkingExample-iOS/VimeoNetworkingCommonTests/VIMVideoTests.swift
[VIM-5563](https://vimean.atlassian.net/browse/VIM-5563)
It was cumbersome to check all live event states individually and made sense to create a new method that could check for these related states in one easy interface. 
Instead of checking for each individual live event state except for post-broadcast we've add a new `isLiveEventInProgress` convenience method that encompasses these checks. 
Added tests to validate the logic in `isLiveEventInProgress`.
Improved and clarified documentation.
Build and run unit tests.
> VIM-5563: Add isLiveEventInProgress convenience method

- VimeoNetworking/Sources/Models/Subscription.swift
Significantly improve the compile time of the library by specifying the type of the dictionary which saves the compiler from having to figure it out.
N/A
Subscription.swift had a very long compile time in Xcode 9. (> 10s)
By specifying the dictionary type we can reduce the compile time to a few milliseconds.
If the project compiles then the test is complete.
> Improve Compile Time for Subscription.swift

- VimeoNetworking/Sources/Models/VIMVideo.h
- VimeoNetworking/Sources/Models/VIMVideo.m
NA
- Missing new video status "unavailable" so we asserted
- Added new video status
- See Vimeo-iOS client repo
> VIM-XXX: Add “unavailable” status to VIMVideo status dictionary

- VimeoNetworking/Sources/Models/VIMLive.swift
[VIM-5791](https://vimean.atlassian.net/browse/VIN-5791)
This PR adds the `archiveError` case to the `LiveStreamingStatus` enum.
N/A
N/A
N/A
> VIM-5791: Add `archive_error` Case to `LiveStreamingStatus` Enum

- VimeoNetworking/Sources/Models/VIMNotification.h
- VimeoNetworking/Sources/Models/VIMNotificationsConnection.h
- VimeoNetworking/Sources/Models/VIMNotificationsConnection.m
[VIM-5916](https://vimean.atlassian.net/browse/VIM-5916)
Backend has exposed a new property `type_unseen_count`.
Add a new property `type_unseen_count` that will be used in the iOS app to display the right number for the notification badge count.
N/A
> VIM-5916: New property type unseen count.

- VimeoNetworking/Sources/Request.swift
N/A
Removed deprecated `characters` to avoid the following warning:
```
'characters' is deprecated: Please use String or Substring directly
```
- Removed `characters`.
N/A
> Remove characters warning

- VimeoNetworking/Sources/Constants.swift
After some deliberation we decided to restore access to the VimeoBaseURL outside of the VimeoNetworking module 👍
> Changes VimeoBaseURL constant access back to public

- VimeoNetworking/Sources/Constants.swift
- VimeoNetworking/Sources/VimeoSessionManager+Constructors.swift
[VIM-6124](https://vimean.atlassian.net/browse/VIM-6124)
This PR adds another `VimeoSessionManager` static constructor that returns an instance suitable for the share extension to use.
N/A
N/A
N/A
> VIM-6124: Perform Upload Task

- VimeoNetworking/Sources/AuthenticationController.swift
- VimeoNetworking/Sources/Constants.swift
- VimeoNetworking/Sources/Request+Authentication.swift
[VIM-6205](https://vimean.atlassian.net/browse/VIM-6205)
Temporarily update the base URL to point to an internal CI branch: `https://api-2339-mark2.ci.vimeows.com`
**Updated AuthenticationController:**
- Added `marketingOptIn` parameters to our join with Email, and join with Facebook methods.
**Updated Constants:**
- Temporarily commented out the normal base URL and replaced it with our work-in-progress CI branch. 🚨 We won't merge this PR until that work has been merged first.
**Updated Request+Authentication:**
- Added a new constant for the `marketing_opt_in` key.
- Updated the methods to join with Email, and join with Facebook to accept the new `marketingOptIn` parameter. Note that Google auth is handled client-side.
This PR will fail CircleCI until the base branch is restored. 
Steps …
> VIM-6205: Updates join requests

- .swiftlint.yml
- Podfile
- Podfile.lock
- Pods/Manifest.lock
- Pods/Pods.xcodeproj/project.pbxproj
- Pods/SwiftLint/LICENSE
- Pods/Target Support Files/Pods-VimeoNetworkingExample-iOS/Pods-VimeoNetworkingExample-iOS-acknowledgements.markdown
- Pods/Target Support Files/Pods-VimeoNetworkingExample-iOS/Pods-VimeoNetworkingExample-iOS-acknowledgements.plist
- Pods/Target Support Files/Pods-VimeoNetworkingExample-tvOS/Pods-VimeoNetworkingExample-tvOS-acknowledgements.markdown
- Pods/Target Support Files/Pods-VimeoNetworkingExample-tvOS/Pods-VimeoNetworkingExample-tvOS-acknowledgements.plist
- VimeoNetworking/Sources/AccountStore.swift
- VimeoNetworking/Sources/AuthenticationController.swift
- VimeoNetworking/Sources/KeychainStore.swift
- VimeoNetworking/Sources/Models/VIMLiveChatUser.swift
- VimeoNetworking/Sources/Request+Video.swift
- VimeoNetworking/Sources/Response.swift
- VimeoNetworking/Sources/ResponseCache.swift
- VimeoNetworking/Sources/Result.swift
- VimeoNetworking/Sources/VimeoClient.swift
- VimeoNetworking/Sources/VimeoRequestSerializer.swift
- VimeoNetworking/Sources/VimeoSessionManager.swift
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/project.pbxproj
Add initial support for SwiftLint
SwiftLint is being included in this project as a Pod, and will run during the script build phase for both the iOS and tvOS targets. 
We pass the `autocorrect` flag to automatically make changes to our source files to ensure consistency.
**Added SwiftLint to Podfile**
Added version 0.25.0 to the Podfile for both the iOS and tvOS targets.
**Enabled initial rules**
To start with only two rules will be autocorrected:
- trailing_newline
- trailing_whitespace
`trailing_newline` looks at the end of a file for extra newline characters. It ensures that only a single newline exists at the end of the file.
`trailing_whitespace` looks for extra whitespace at the end of a line. It then removes this whitespace.
These two rules were chosen for their low impact and lack …
> Add initial support for SwiftLint

- VimeoNetworking/Sources/ResponseCache.swift
- VimeoNetworking/Sources/VimeoClient.swift
- VimeoNetworkingExample-iOS/VimeoNetworkingCommonTests/ResponseCacheTests.swift
[AF-243](https://vimean.atlassian.net/browse/AF-243)
*Note: this is required for Vimeo staff only. If not applicable to your PR, use "N/A".*
Removes most of the code for the ResponseCache, leaving its only function to clean up old caches.
**ResponseCache:**
- Removed almost the entire class.
- The only functions left serve to clean up old caches.
**ResponseCacheTests:**
- Removed old tests.
- Added test to verify `clean()` function removes caches on disk as expected.
Also fixed some documentation and formatting things that were bugging me 👋😬👍
Removed references to the **ResponseCache** in **AuthenticationController**, and **VimeoClient**, 
- Build and run.
- Ensure tests pass.
> AF-243: Refactors ResponseCache and related tests

- VimeoNetworking/Sources/Models/VIMUserBadge.h
- VimeoNetworking/Sources/Models/VIMUserBadge.m
[VIM-6317](https://vimean.atlassian.net/browse/VIM-6317)
- Remove the badge Type Pro Unlimited because PRO and PRO Unlimited use the same badge type
- Updated the enum badge type.
See main PR.
> VIM-6317: Remove the badgeType Pro Unlimited

- VimeoNetworking/Sources/Request+Authentication.swift
- VimeoNetworking/Sources/Request+Cache.swift
- VimeoNetworking/Sources/Request+Notifications.swift
- VimeoNetworking/Sources/Request+Picture.swift
- VimeoNetworking/Sources/Request+Trigger.swift
- VimeoNetworking/Sources/VimeoRequestSerializer.swift
N/A
- Using `+` with string literals has poor type-checking performance, see [here](https://github.vimeows.com/MobileApps/Style-Guides/pull/34).
- Wherever we had `+` used with string literals, use string interpolation instead.
- Make sure interpolation replacements preserve semantics!
> Replace use of '+' with string interpolation

- Pods/Pods.xcodeproj/project.pbxproj
- VimeoNetworking/Sources/Models/VIMConnection.h
- VimeoNetworking/Sources/Models/VIMConnection.m
- VimeoNetworking/Sources/Models/VIMTextTrack.swift
[VIM-6383](https://vimean.atlassian.net/browse/VIM-6383)
- Make the necessary client side changes to fetch and work with text track objects from the API.
- Add `texttracks` connection.
- Pull `VIMTextTrack` model object in from Vimeo-MacOS.
- Yes, the API spells this as `texttracks`, not `text_tracks`.
> VIM-6383: Create new VIMTextTrack model object

- VimeoNetworking/Sources/VimeoResponseSerializer.swift
[VIM-6406](https://vimean.atlassian.net/browse/VIM-6406)
- We should download the text track objects from the API before we initiate the download if there are any available.
- Add the content type of the text tracks response to the `acceptableContentTypes()` return value.
> VIM-6406: In DownloadManager, fetch any text tracks before initiating download

- Pods/Pods.xcodeproj/project.pbxproj
- VimeoNetworking/Sources/Models/Album.swift
- VimeoNetworking/Sources/VimeoResponseSerializer.swift
- VimeoNetworkingExample-iOS/VimeoNetworkingCommonTests/AlbumTests.swift
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/project.pbxproj
- VimeoNetworkingExample-iOS/album-response.json
[VIM-6642](https://vimean.atlassian.net/browse/VIM-6642)
Add the Album model object to VimeoNetworking.
- Added **Album.swift** model object.
- Added **album-response.json** fixture for testing.
- Added unit tests covering parsing for the Album object, including date formatting, album logo unwrapping, and embed HTML verification.
- Build & run unit tests.
> VIM-6642: Adds support for Albums

- Pods/Pods.xcodeproj/project.pbxproj
- VimeoNetworking/Sources/Models/Spatial.swift
- VimeoNetworking/Sources/Models/Subscription.swift
- VimeoNetworking/Sources/Models/SubscriptionCollection.swift
- VimeoNetworking/Sources/Models/UserMembership.swift
- VimeoNetworking/Sources/Models/UserSubscription.swift
- VimeoNetworking/Sources/Models/UserSubscriptionRenewal.swift
- VimeoNetworking/Sources/Models/UserSubscriptionTrial.swift
- VimeoNetworking/Sources/Models/VIMLiveQuota.swift
- VimeoNetworking/Sources/Models/VIMProgrammedContent.swift
- VimeoNetworking/Sources/Models/VIMUploadQuota.swift
- VimeoNetworking/Sources/Models/VIMUser.h
- VimeoNetworking/Sources/Models/VIMUser.m
- VimeoNetworkingExample-iOS/VIMUser/VIMUserBadgeTests.swift
- VimeoNetworkingExample-iOS/VIMUser/VIMUserTests.swift
- VimeoNetworkingExample-iOS/VIMUser/user_alum.json
- VimeoNetworkingExample-iOS/VIMUser/user_basic.json
- VimeoNetworkingExample-iOS/VIMUser/user_basic_had_free_trial.json
- VimeoNetworkingExample-iOS/VIMUser/user_business.json
- VimeoNetworkingExample-iOS/VIMUser/user_curation.json
- VimeoNetworkingExample-iOS/VIMUser/user_live_business.json
- VimeoNetworkingExample-iOS/VIMUser/user_live_premium.json
- VimeoNetworkingExample-iOS/VIMUser/user_live_pro.json
- VimeoNetworkingExample-iOS/VIMUser/user_plus.json
- VimeoNetworkingExample-iOS/VIMUser/user_pro.json
- VimeoNetworkingExample-iOS/VIMUser/user_pro_unlimited.json
- VimeoNetworkingExample-iOS/VIMUser/user_producer.json
- VimeoNetworkingExample-iOS/VIMUser/user_staff.json
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/project.pbxproj
- VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/user_live.json
[AF-322](https://vimean.atlassian.net/browse/AF-322)
This PR updates the VIMUser object to represent the data returned by the Vimeo API version 3.4.2.  This includes adding a new Membership object which contains information about the user's badge, account type, and subscription status, as well as removing deprecated properties like account and badge from the root of the VIMUser object.  I've also updated a few files that were missing our license information.
UserMembership.swift
- A new class that represents the account and membership information for a user. 
- Added a property for VIMUserBadge which replaces the VIMUser.badge property
- Added a type property which replaces the VIMUser.account property
- Added a UserSubscription object which holds information about the user's subscription …
> AF-322: Adds membership information to the VIMUser object

- VimeoNetworking/Sources/Models/UserMembership.swift
- VimeoNetworking/Sources/Models/VIMModelObject.h
- VimeoNetworking/Sources/Models/VIMModelObject.m
- VimeoNetworking/Sources/Models/VIMUser.m
- VimeoNetworking/Sources/Models/VIMVODItem.m
- VimeoNetworking/Sources/Models/VIMVideo.m
[VIM-6817](https://vimean.atlassian.net/browse/VIM-6817)
A crash was found in Vimeo iOS due to a lack of migration code from the previous VIMUser object which contained the VIMUserBadge object and a NSString property called "account" in the root of the object to the current object which has a UserMembership object that nests the badge and account info.  This problem occurred when we attempted to read a serialized user object from disk and decoded it using NSCoder. 
VIMModelObject.h
- Updated the declaration for upgradeFromModelVersion to include the NSCoder object being used to deserialize the object.  This is needed if we're attempting to read in information from the stored object that no longer exists in the current model.
VIMModelObject.m
- Added a changelog comment section for the …
> VIM-6817: Adds migration code to VIMUser object to update membership info

- VimeoNetworking/Sources/Models/VIMVideo.h
- VimeoNetworking/Sources/Models/VIMVideo.m
N/A
This PR adds a method to check if there's a file transfer page.
The implementation of this method checks:
- If `fileTransfer` response is `nil`.
- If the URL inside the response exists.
- If `canDownload` privacy setting is enabled.
N/A
N/A
> VIM-XXXX: Add Method to Check If There's File Transfer Page

- VimeoNetworking/Sources/Request+Album.swift
- VimeoNetworking/Sources/Request+PasswordProtected.swift
- VimeoNetworking/Sources/Request+Video.swift
[VIM-6642](https://vimean.atlassian.net/browse/VIM-6642)
Add support for access password-protected albums.
**Request+PasswordProtected.swift**: 
Created a new extension on `Request` to return a request object for both `VIMVideo` and `Album` requests that require sending a password for access.
**Request+Album.swift**: 
Update the API and documentation for that static `albumRequest(for uri: String)` method.
n/a
> VIM-6642: Creates generalized method for creating password-protected requests

- VimeoNetworking/Sources/Models/VIMPrivacy.h
- VimeoNetworking/Sources/Models/VIMPrivacy.m
- VimeoNetworking/Sources/Models/VIMVideo.h
- VimeoNetworking/Sources/Models/VIMVideo.m
- VimeoNetworkingExample-iOS/VimeoNetworkingCommonTests/VIMVideoTests.swift
[VIM-6849](https://vimean.atlassian.net/browse/VIM-6849)
Add support for allowing `VIMVideo` objects to report whether or not they represent a stock video clip.
**VIMPrivacy**:
Added a new string to the existing privacy options.
**VIMVideo**:
Added a convenience method to return whether a video is stock or not. Also updated the `isPrivate()` method to ensure that stock videos are not considered private.
Build and run the example project, ensure tests pass.
> VIM-6849: Adds support for identifying stock videos

- VimeoNetworking/Sources/Models/VIMObjectMapper.m
[VIM-6694](https://vimean.atlassian.net/browse/VIM-6694)
This branch moves the changes from this PR (https://github.com/vimeo/VimeoNetworking/pull/282) into a new branch from develop.  The old PR branch had a bad rebase on it which is making the diff look weird.  The only change that should be coming back to develop is the check for nil before adding an object into an array in VIMObjectMapper.  I changed the code from using NSLogs to NSAsserts, which was my feedback on the last PR. 
- Adds a nil check before attempting to add an object into an NSArray
- Replaces NSLog usage with NSAssert.
- make sure unit tests continue to pass
> VIM-6694: Moving outdated PR to a new branch after a bad rebase attempt

- VimeoNetworking/Sources/Scope.swift
Numerous requests have been made ([here](https://github.com/vimeo/VimeoNetworking/issues/207), [here](https://github.com/vimeo/VimeoNetworking/issues/259), and [here](https://github.com/vimeo/VimeoNetworking/issues/306)) to add the `video_files` scope to VimeoNetworking, as this is the only way for an API app to access video files on a `VIMVideo` object. 
This pull request updates the implementation of the `Scope` enum in the following ways:
- Adds the `video_files` scope and maps it to the `VideoFiles` case.
- Adds the `promo_codes` scope and maps it to the `PromoCodes` case.
- Declares `Scope` as `CaseIterable`.
- Updated documentation to match the copy found at [developer.vimeo.com](https://developer.vimeo.com/api/authentication).
More information about scopes can be found …
> Adds the VideoFiles and PromoCodes scopes, updates documentation

- VimeoNetworking/Sources/Models/Album.swift
- VimeoNetworking/Sources/Models/VIMPrivacy.h
- VimeoNetworkingExample-iOS/VimeoNetworkingCommonTests/AlbumTests.swift
[VIM-6975](https://vimean.atlassian.net/browse/VIM-6975)
- Showcases store the password directly on the VIMPrivacy object, rather than as a field on the showcase model
- Add a new `password` field to `VIMPrivacy`
- Add new test
- Will be tested as part of main Vimeo-iOS PR
- Project should build and unit tests should pass
> VIM-6975: Add password field to VIMPrivacy

- Sources/Shared/Models/VIMLiveChatUser.swift
- Sources/Shared/Models/VIMUser.h
- Sources/Shared/Models/VIMUser.m
- Sources/Shared/Models/VIMUserAccountType.swift
- Tests/Shared/VIMLiveTests.swift
- Tests/Shared/VIMUserAccountTypeTests.swift
- Tests/Shared/VIMUserTests.swift
- VimeoNetworking.xcodeproj/project.pbxproj
[VIM-7124](https://vimean.atlassian.net/browse/VIM-7124
This PR adds a new account type `Enterprise` to the `VIMAccountType` model.
It also modifies a switch case on account type returning the appropriate string for enterprise users.
While making this change I've taken the opportunity to improve some of the logic related to handling account types. 
We had some code duplication under `VIMLiveChatUser.swift` that has been removed in favor of a refactored `VIMUserAccountType` that is now migrated to Swift.
Due to the fact that this enum is used across both Swift and Objective-C, its raw type must be `Int`. We have also forward declared the enum in the `VIMUser` header file, and created a couple of Objective-C bridging methods for convenience.
Finally, unit tests have been added to verify the …
> VIM-7124: Adds enterprise account type to user

- fastlane/Fastfile
[VIM-XXXX](https://vimean.atlassian.net/browse/VIM-XXXX)
This PR address an issue with fork PRs that always fail due to Circle CI correctly not exposing sensitive environment variables.
Danger uses a github access token to comment on pull requests. The access token is set and obtained via an environment variable that is not available to forks.
Because of that, all PR builds that come from forks fail and are not mergeable, requiring us to manually cherry pick changes, create a new PR and give credit to
the person that originally submitted it.
This PR makes changes to our build lane on `fastlane` so we opt out of running `danger` on fork PRs.
We achieve this by checking the CIRCLE_BRANCH environment variable, and searching for a pattern of `pull/XXXX` where XXXX is a numeric value.
If a …
> Fixes issue with fork PRs never succeeding

- VimeoNetworking.xcodeproj/project.pbxproj
- VimeoNetworking.xcodeproj/xcshareddata/xcschemes/VimeoNetworking-macOS.xcscheme
- VimeoNetworking.xcodeproj/xcshareddata/xcschemes/VimeoNetworking-tvOS.xcscheme
We continue to experience non-deterministic build issues when using xcodebuild, and consequently also Carthage.
After a lot of time wasted trying to solve this I ended up finding [this issue](https://github.com/CocoaPods/CocoaPods/issues/8729#issuecomment-510876724).
As described in the link above, I believe what we are seeing is due to an underlying xcodebuild bug. The current accepted work around for the problem is to explicitly specify the dependencies for a given scheme rather than let Xcode find them implicitly.
This is the open radar link for this issue https://openradar.appspot.com/20490378
I found the best way to test this PR is to try and build it with carthage multiple times, making sure that the carthage cache is removed before each build:
```
rm -rf ~/Library/Caches/carthage …
```
> Fixes implicit dependency build issues
