vimeo/VimeoNetworking

VimeoNetworking/VimeoNetworking.xcodeproj/project.pbxproj
VimeoNetworking/VimeoNetworking/NSURLSessionConfiguration+Extensions.swift
VimeoNetworking/VimeoNetworking/VimeoSessionManager+Constructors.swift

Merging in the fix for the caching issue that was causing the Video list request to return videos for the wrong user.  This fix has already been pulled back into master, but we also need it on the cameo branch.
Merging in rev. eb61617df18a9696971fc2ffebf92bb977faae14 from master.

cameo-merge-cache-fix

---

VimeoNetworking/VimeoNetworking/VimeoClient.swift

[TVOS-14](https://vimean.atlassian.net/browse/TVOS-14)
Port stream data source logic from iOS to tvOS. This will eliminate VIMNetworking from our stream logic and replace it with VimeoNetworking.
- Added remove cache for `Request` method
See app-side PRs

Adding cache removal method

---

VimeoNetworking/VimeoNetworking/AuthenticationController.swift
VimeoNetworking/VimeoNetworking/ResponseCache.swift

[CAM-414](https://vimean.atlassian.net/browse/CAM-414)
Updating the code so it will compile on Xcode 8 beta 6 for iOS 10
Some methods in the NSURL class now return optional values that need to be unwrapped.
N/A

CAM-414: Fixing issues with iOS 10

---

VimeoNetworking/VimeoNetworking/Models/VIMVideoFile.h

This commit adds the secure link for for the VIMVideoFile class.

Add secure link for VIMVideoFile

---

VimeoNetworking/VimeoNetworking/AuthenticationController.swift
VimeoNetworking/VimeoNetworking/VimeoClient.swift

Implements some changes to our authentication controller to clear the Client's cache when the current authenticated user changes.

Clearing cache on appropriate authentication changes

---

VimeoNetworking/VimeoNetworking/Models/VIMConnection.h
VimeoNetworking/VimeoNetworking/Models/VIMConnection.m

[VIM-4561](https://vimean.atlassian.net/browse/VIM-4561)
Added a new connection constant for categories.
Added a new connection constant for categories.
N/A

VIM-4561:  Add support for the category connection on user

---

VimeoNetworking/VimeoNetworking/Models/VIMConnection.h
VimeoNetworking/VimeoNetworking/Models/VIMConnection.m

[VIM-4561](https://vimean.atlassian.net/browse/VIM-4561)
Added a new connection constant for categories.
Added a new connection constant for categories.
N/A

VIM-4561: Add support for the category connection on user

---

VimeoNetworking/VimeoNetworking.xcodeproj/project.pbxproj
VimeoNetworking/VimeoNetworking/AuthenticationController.swift
VimeoNetworking/VimeoNetworking/Models/VIMVideo.m
VimeoNetworking/VimeoNetworking/Models/VIMVideoProgressiveFile.h
VimeoNetworking/VimeoNetworking/ResponseCache.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/project.pbxproj

This PR merges in the changes necessary to get VimeoNetworking building for Xcode 8.  It also fixes a number of build issues that currently exist on the branch.

Merging in Xcode 8 fixes from Cameo branch

---

VimeoNetworking/VimeoNetworking/Models/VIMConnection.h
VimeoNetworking/VimeoNetworking/Models/VIMConnection.m

N/A
Added the moderated channels connection constant. 
Added the moderated channels connection constant. 
N/A

No ticket: Add connection for moderated channels

---

VimeoNetworking/VimeoNetworking/Models/VIMConnection.h
VimeoNetworking/VimeoNetworking/Models/VIMConnection.m
VimeoNetworking/VimeoNetworking/Models/VIMModelObject.h
VimeoNetworking/VimeoNetworking/Models/VIMModelObject.m
VimeoNetworking/VimeoNetworking/Models/VIMObjectMapper.m
VimeoNetworking/VimeoNetworking/Models/VIMSeason.h
VimeoNetworking/VimeoNetworking/Models/VIMSeason.m
VimeoNetworking/VimeoNetworking/VimeoResponseSerializer.swift

[TVOS-385](https://vimean.atlassian.net/browse/TVOS-385)
Add Dynamic streams support to the tvOS app for use in VOD seasons
This VimeoNetworking PR adds the changes necessary to request seasons from VOD items

TVOS-385: VOD Seasons Support

---

VimeoNetworking/VimeoNetworking/Models/VIMConnection.h
VimeoNetworking/VimeoNetworking/Models/VIMConnection.m

[TVOS-349](https://vimean.atlassian.net/browse/TVOS-349)
Adds a stream of the user's previously watched videos to the Library tab on tvOS
Added some connection constants for Watch History

TVOS-349: Adding watched videos connection

---

VimeoNetworking/VimeoNetworking/Request+Trigger.swift
VimeoNetworking/VimeoNetworking/VimeoRequestSerializer.swift

https://vimean.atlassian.net/browse/VIM-4334
Convert push notification settings to VimeoNetworking.
Converted SMKPushNotificationsCenter to the new VimeoNetworking methods from the "pass 1" PR.
Go into settings and make sure push notification settings work as expected.

VIM-4334: VimeoNetworking Push Notification Settings Pass 2

---

VimeoNetworking/VimeoNetworking/VimeoClient.swift
VimeoNetworking/VimeoNetworking/VimeoReachability.swift

N/A
This is just some final cleanup after merging in the VimeoNetworking conversion.
- Moved VimeoReachability into VimeoNetworking
N/A

Porting VimeoNetworking Conversion Changes to TV

---

VimeoNetworking/VimeoNetworking/Constants.swift
VimeoNetworking/VimeoNetworking/Models/VIMVideoPlayFile.h
VimeoNetworking/VimeoNetworking/Models/VIMVideoPlayFile.m

https://vimean.atlassian.net/browse/TVOS-404
Implement play logging.
Updates for the new API spec.
Play videos and make sure "Play Log Success" is logged each time a video completes.

TVOS-404: Play Logging

---

VimeoNetworking/VimeoNetworking/Constants.swift
VimeoNetworking/VimeoNetworking/Models/VIMVideoPlayFile.h
VimeoNetworking/VimeoNetworking/Models/VIMVideoPlayFile.m

https://vimean.atlassian.net/browse/VIM-4732
Merge in the localization branch.
Fixed a play logging issue while I was in there.
N/A

VIM-4732: Localization Merge

---

VimeoNetworking/VimeoNetworking/Models/VIMVideoPlayFile.m

Moving this code to VimeoUpload. See https://github.com/vimeo/VimeoUpload/pull/123

VIM-XXXX: 6.1.4 NSKeyedArchiver Migration Bug

---

VimeoNetworking/Sources/ErrorCode.swift

[VIM-4582](https://vimean.atlassian.net/browse/VIM-4582)
Handle error codes for batch follow listed here: 
https://docs.google.com/spreadsheets/d/1DlkbeOFDuogvwyG2QDqExqBd_Yb3M7w7ku25AJN7QU0/edit#gid=0
- added codes
N/A

VIM-4582: Handle Batch Follow Errors

---

VimeoNetworking/Sources/VimeoResponseSerializer.swift
VimeoNetworking/VimeoNetworking/Models/SubscriptionCollection.swift
VimeoNetworking/VimeoNetworking/Request+Notifications.swift

https://vimean.atlassian.net/browse/VIM-4830
Retrieve SubscriptionCollection and Subscription objects for Notifications.
Added a new object in VimeoNetworking to retrieve the SubscriptionCollection datas.
Added a new object in VimeoNetworking to retrieve the Subscription datas.
Make this Call and print the values in `notif`:
```
let subscription = Subscription()
subscription.comment = true
VimeoClient.sharedClient.request(Request<SubscriptionCollection>.updateNotificationSubscriptions(subscription), completion: { result in
switch result
{
case .Success(let result):                
let notif = result.model
case .Failure(let error):
let alert = VIMAlert.errorAlert(error: error)
}
})
```

VIM-4830: Notification settings networking

---

VimeoNetworking/Sources/Models/VIMConnection.h
VimeoNetworking/Sources/Models/VIMConnection.m
VimeoNetworking/Sources/Models/VIMCredit.h
VimeoNetworking/Sources/Models/VIMCredit.m
VimeoNetworking/Sources/Models/VIMNotification.h
VimeoNetworking/Sources/Models/VIMNotification.m
VimeoNetworking/Sources/VimeoResponseSerializer.swift

[VIM-4847](https://vimean.atlassian.net/browse/VIM-4847)
As a developer, I would like to create a Notification model
- Added `VIMNotification` class
- Added `VIMCredit` class
- Added `VIMConnectionNameNotifications` key
- Added `application/vnd.vimeo.notification+json` to acceptable content types

VIM-4847: Add Notification model

---

VimeoNetworking/Sources/Models/VIMVideo.m

See https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/1165

VIM-4764: Adding 360 DRM Error

---

VimeoNetworking/Sources/Models/VIMVideo+SVOD.h
VimeoNetworking/Sources/Models/VIMVideo+SVOD.m

https://vimean.atlassian.net/browse/TVOS-709
Added an extension to VIMVideo for SVOD.
- Implemented `isSVOD()`
- Implemented `svodAccess()`
N/A

TVOS-709: Added an extension to VIMVideo for SVOD

---

VimeoNetworking/Sources/Request+Notifications.swift

See the main ticket: https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/1260

VIM-4860: Multiple Devices

---

VimeoNetworking/Sources/Models/SubscriptionCollection.swift

[VIM-5128](https://vimean.atlassian.net/browse/VIM-5128)
Remove modifiedTime property to resolve a crash
Remove modifiedTime property. Add migrated property.

[VIM-5128] Remove modifiedTime property. Add migrated property.

---

VimeoNetworking/Sources/Models/VIMUser.h
VimeoNetworking/Sources/Models/VIMUser.m

Companion PR to https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/1324

VIM-4712: Adding action sheet option to add to channel

---

VimeoNetworking/Sources/Request+Cache.swift

See https://github.com/vimeo/VimeoNetworking/pull/133 description.

TVOS-732: Updated cacheKey

---

VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VimeoClientTests.swift

- Reintegrating any changes from the release 2.0.0 branch.

Release 2.0.0 reintegration

---

VimeoNetworking/Sources/VimeoRequestSerializer.swift

https://vimean.atlassian.net/browse/AF-83
Add the framework string to the user agent: https://github.vimeows.com/Vimeo-API/api/issues/1141#issuecomment-143572
Appending the framework name and version.
Set a breakpoint to make sure the user agent looks like it should (described in the ticket).

AF-83: Modifying User Agent

---

VimeoNetworking/Sources/Models/Subscription.swift
VimeoNetworking/Sources/Models/VIMNotification.h
VimeoNetworking/Sources/Models/VIMNotification.m

Reverts vimeo/VimeoNetworking#138

Revert "VIM-5110: Added a new VIMNotificationType."

---

VimeoNetworking/Sources/Models/Subscription.swift
VimeoNetworking/Sources/Models/VIMNotification.h
VimeoNetworking/Sources/Models/VIMNotification.m

Reverts vimeo/VimeoNetworking#157

Revert "Revert "VIM-5110: Added a new VIMNotificationType.""

---

VimeoNetworking/Sources/Models/VIMQuantityQuota.m
VimeoNetworkingExample-iOS/VimeoNetworkingCommonTests/VIMQuantityQuota+Tests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingCommonTests/VIMUploadQuota+Tests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/project.pbxproj

- Re-integrates bug fixes that were made on the release/3.0.1 branch.

Merge release/3.0.1 re-integration branch

---

VimeoNetworking/Sources/VimeoClient.swift

[VIM-5574](https://vimean.atlassian.net/browse/VIM-5574)
This PR opens up the scope of `RequestToken`'s `task` property for testing the video-refreshing code.
N/A
N/A
N/A

VIM-5574: Implement Video-Refreshing Mechanism

---

Podfile.lock
Pods/Local Podspecs/VimeoNetworking.podspec.json
Pods/Manifest.lock
Pods/Target Support Files/VimeoNetworking-iOS/Info.plist
Pods/Target Support Files/VimeoNetworking-tvOS/Info.plist
VimeoNetworking.podspec

[AF-123](https://vimean.atlassian.net/browse/AF-123)
- Fix the version number in the pod spec file so the correct version is displayed when running pod install.
- VimeoNetworking.podspec - fixed the version number
- The only actual change was to the VimeoNetworking.podspec file, the other changes are from running `bundle exec pod install`

Updates version number to match latest release

---

circle.yml
fastlane/Fastfile

N/A
- Switch to using Xcode 9
- Update the circle yams file to use Xcode 9

Upgrade to Xcode 9

---

VimeoNetworking/Sources/Models/VIMConnection.h
VimeoNetworking/Sources/Models/VIMConnection.m
VimeoNetworking/Sources/Scope.swift

[VIM-5602](https://vimean.atlassian.net/browse/VIM-5602)
The goal of this PR is to introduce a new connection for Live Stats.
- `VIMConnection`: added a new constant associated with the new connection from the API response.
N/A
N/A

VIM-5602: Introduce New Connection for Live Stats

---

Pods/Pods.xcodeproj/project.pbxproj
VimeoNetworking/Sources/Models/VIMLive.swift
VimeoNetworking/Sources/Models/VIMLiveChat.swift
VimeoNetworking/Sources/Models/VIMLiveChatUser.swift
VimeoNetworking/Sources/Models/VIMLiveUser.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/project.pbxproj
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/MockConstants.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VIMLiveHeartbeatTests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VIMLiveQuotaTests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VIMLiveTests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/clip_live.json
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/user_live.json

[VIM-5581](https://vimean.atlassian.net/browse/VIM-5581)
The goal of this PR is to add new Vimeo models for the "Live Chat" feature.
I added new unit tests for checking the parsing of new models.
N/A
Verify that all unit tests pass.

VIM-5581: Add New Models for Live Chat

---

VimeoNetworking/Sources/Models/PinCodeInfo.swift
VimeoNetworking/Sources/Models/PlayProgress.swift
VimeoNetworking/Sources/Models/Spatial.swift
VimeoNetworking/Sources/Models/Subscription.swift
VimeoNetworking/Sources/Models/SubscriptionCollection.swift
VimeoNetworking/Sources/Models/VIMLive.swift
VimeoNetworking/Sources/Models/VIMLiveHeartbeat.swift
VimeoNetworking/Sources/Models/VIMLiveQuota.swift
VimeoNetworking/Sources/Models/VIMLiveStreams.swift
VimeoNetworking/Sources/Models/VIMLiveTime.swift
VimeoNetworking/Sources/Models/VIMProgrammedContent.swift

See https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/1638

VIM-XXX: @objc Audit

---

VimeoNetworking/Sources/Models/VIMInteraction.h
VimeoNetworking/Sources/Models/VIMInteraction.m
VimeoNetworking/Sources/VimeoResponseSerializer.swift

N/A
This PR contains IAP work.
N/A
N/A
N/A

In-App Purchase

---

VimeoNetworking/Sources/Request+Video.swift

[VIM-4099](https://vimean.atlassian.net/browse/VIM-4099)
- Fixed broken selected users request url. See https://developer.vimeo.com/api/endpoints/videos under "Get all users who can view a private video"
- Added path component
- See Vimeo-iOS PR https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/1800

VIM-4099: Fix selected users privacy request

---

VimeoNetworking/Sources/Models/VIMNotificationsConnection.m

https://vimean.atlassian.net/browse/VIM-5996
See ticket.
Added a migration to resolve the wrong type issue.
This is hard to test without a malformed user. I have already tested locally by manually modifying the user object.

VIM-5996: Adding `type_count` migration

---

VimeoNetworking/Sources/ErrorCode.swift

[VIM-5984](https://vimean.atlassian.net/browse/VIM-5984)
Added a new error code `uploadQuotaSizeExceededCap`.
Updated the Error code enum.
N/A

VIM-5984: Add a new error code.

---

VimeoNetworking/Sources/Models/VIMUser.h
VimeoNetworking/Sources/Models/VIMUser.m
VimeoNetworkingExample-iOS/VIMUser/VIMUserTests.swift
VimeoNetworkingExample-iOS/VIMUser/user_live_premium.json
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/project.pbxproj

[VIM-6044](https://vimean.atlassian.net/browse/VIM-6044)
This PR adds a new enum case to handle the new "Premium Live" account tier.
Added a new test for "Premium Live" account tier.
N/A
Run all unit tests. Check that all of them pass.

VIM-6044: Handle "Premium" Account

---

Podfile.lock
Pods/Local Podspecs/VimeoNetworking.podspec.json
Pods/Manifest.lock
Pods/Pods.xcodeproj/project.pbxproj
Pods/Target Support Files/VimeoNetworking-iOS/Info.plist
Pods/Target Support Files/VimeoNetworking-tvOS/Info.plist

Run pod install

---

VimeoNetworking/Sources/Models/VIMConnection.h
VimeoNetworking/Sources/Models/VIMConnection.m

[VIM-6351](https://vimean.atlassian.net/browse/VIM-6351)
- Main ticket is for adding analytics to the CC feature. This enables part of that implementation.
- Add connection name for text tracks.

VIM-6351: Analytics for CC

---

VimeoNetworking/Sources/Models/VIMUser.h
VimeoNetworking/Sources/Models/VIMUser.m
VimeoNetworking/Sources/Models/VIMUserBadge.h
VimeoNetworking/Sources/Models/VIMUserBadge.m
VimeoNetworkingExample-iOS/VIMUser/VIMUserTests.swift
VimeoNetworkingExample-iOS/VIMUser/user_pro_unlimited.json
VimeoNetworkingExample-iOS/VIMUser/user_producer.json
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/project.pbxproj

[VIM-6316](https://vimean.atlassian.net/browse/VIM-6316)
Add an account type: Pro Unlimited.
Updated the VIMUserAccountType enum.
N/A

VIM-6316: Add new account type pro unlimited / Producer

---

VimeoNetworking/Sources/Models/VIMConnection.h
VimeoNetworking/Sources/Models/VIMConnection.m

Reverts vimeo/VimeoNetworking#243

Revert "VIM-6351: Analytics for CC"

---

README.md
VimeoNetworking.podspec

Preparing to release version 3.2.0.
- Updated our ReadMe instructions in anticipation of pushing to Trunk.
- Added Freddy as an author 👋
- Updated the version number in the Podspec.

AF-305: VimeoNetworking 3.2.0

---

VimeoNetworking.podspec

Updates Podspec in preparation for releasing version 3.3.0.

Update Podspec version number to 3.3.0

---

Podfile.lock
Pods/Local Podspecs/VimeoNetworking.podspec.json
Pods/Manifest.lock
Pods/Target Support Files/VimeoNetworking-iOS/Info.plist
Pods/Target Support Files/VimeoNetworking-tvOS/Info.plist

- Ran `bundle exec pod update` to ensure Podfile.lock and related files point to the latest release.

Run bundle exec pod update

---

Pods/Pods.xcodeproj/project.pbxproj
VimeoNetworking/Sources/AuthenticationController.swift
VimeoNetworking/Sources/ClosureTypes.swift
VimeoNetworking/Sources/VimeoClient.swift
VimeoNetworking/Sources/VimeoSessionManager+Constructors.swift
VimeoNetworkingExample-iOS/VIMUser/VIMUserBadgeTests.swift
VimeoNetworkingExample-iOS/VIMUser/VIMUserTests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingCommonTests/Request+ProgrammedContent.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS/AppDelegate.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS/MasterViewController.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS/VimeoClient+Shared.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VIMLiveHeartbeatTests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VIMLiveQuotaTests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VIMLiveTests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VimeoClientTests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VimeoSessionManagerTests.swift

n/a
n/a
Merges release into develop
Project should build and unit tests should pass

Merges 6.31.1 (integration with develop branch) into develop

---

Pods/Pods.xcodeproj/project.pbxproj
VimeoNetworking/Sources/AuthenticationController.swift
VimeoNetworking/Sources/ClosureTypes.swift
VimeoNetworking/Sources/VimeoClient.swift
VimeoNetworking/Sources/VimeoSessionManager+Constructors.swift
VimeoNetworkingExample-iOS/VIMUser/VIMUserBadgeTests.swift
VimeoNetworkingExample-iOS/VIMUser/VIMUserTests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingCommonTests/Request+ProgrammedContent.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS/AppDelegate.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS/MasterViewController.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS/VimeoClient+Shared.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VIMLiveHeartbeatTests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VIMLiveQuotaTests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VIMLiveTests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VimeoClientTests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/VimeoSessionManagerTests.swift

n/a
n/a
Merges release into feature branch
Project should build and unit tests should pass

Merges 6.31.1 into 7.0.0

---

VimeoNetworking/Sources/Models/VIMVideoPlayRepresentation.h
VimeoNetworking/Sources/Models/VIMVideoPlayRepresentation.m

[VIM-6552](https://vimean.atlassian.net/browse/VIM-6552)
This PR adds the `password` playability status.
N/A
N/A
N/A

VIM-6552: Add `password` Playability Status

---

Gemfile
Gemfile.lock

[VIM-6695](https://vimean.atlassian.net/browse/VIM-6695)
Updates nokogiri to the latest version to address a security issue.
- Bumped up the nokogiri version to 1.8.5 in the Gemfile

updates nokogiri to latest version

---

VimeoNetworking/Sources/VimeoResponseSerializer.swift

[VIM-6776](https://vimean.atlassian.net/browse/VIM-6776)
This PR adds an acceptable content type for Stats.
N/A
N/A
N/A

VIM-6776: Add Acceptable Content Type for Stats

---

VimeoNetworking/Sources/Models/VIMUser.m

Per feedback from Mike, we should avoid the version check at the network layer.

Revert "VIM-6828: Add free trial copy to purchase flow UI"

---

Pods/Pods.xcodeproj/project.pbxproj
VimeoNetworking/Sources/Constants.swift
VimeoNetworking/Sources/Models/FileTransfer.swift
VimeoNetworking/Sources/Models/VIMVideo.h
VimeoNetworking/Sources/Models/VIMVideo.m
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/project.pbxproj
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/FileTransferTests.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/clip.json

[VIM-6824](https://vimean.atlassian.net/browse/VIM-6824)
This PR adds new data model for file transfer.
N/A
N/A
N/A

VIM-6824: Add File Transfer Data Model

---

VimeoNetworking.podspec
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS/Info.plist
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/Info.plist
VimeoNetworkingExample-iOS/VimeoNetworkingExample-tvOS/Info.plist
VimeoNetworkingExample-iOS/VimeoNetworkingExample-tvOSTests/Info.plist

Updates the VimeoNetworking pod and project file to version 3.4.0 in preparation for the next release.

Updates version to 3.4.0

---

VimeoNetworking/Sources/VimeoResponseSerializer.swift

[VIM-6719](https://vimean.atlassian.net/browse/VIM-6719)
This PR merges Stats phase 1 work into `develop`.
N/A
N/A
N/A

VIM-6719: Stats Phase 1

---

.circleci/config.yml
README.md
VimeoNetworking.podspec
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/project.pbxproj
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS/Info.plist
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOSTests/Info.plist
VimeoNetworkingExample-iOS/VimeoNetworkingExample-tvOS/Info.plist
VimeoNetworkingExample-iOS/VimeoNetworkingExample-tvOSTests/Info.plist
fastlane/Fastfile
fastlane/README.md

Testing to see if integration branch will resolve the CI hangup
Original PR opened and reviewed here: 
https://github.com/vimeo/VimeoNetworking/pull/312

Master into Develop

---

VimeoNetworking/Sources/NSError+Extensions.swift
VimeoNetworking/Sources/Request+Album.swift
VimeoNetworking/Sources/Request+Category.swift
VimeoNetworking/Sources/Request+Channel.swift
VimeoNetworking/Sources/Request+Comment.swift
VimeoNetworking/Sources/Request+Notifications.swift
VimeoNetworking/Sources/Request+Picture.swift
VimeoNetworking/Sources/Request+PolicyDocument.swift
VimeoNetworking/Sources/Request+ProgrammedContent.swift
VimeoNetworking/Sources/Request+Soundtrack.swift
VimeoNetworking/Sources/Request+Toggle.swift
VimeoNetworking/Sources/Request+User.swift
VimeoNetworking/Sources/Request+Video.swift
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/project.pbxproj
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/xcshareddata/xcschemes/VimeoNetworkingExample-iOS.xcscheme
VimeoNetworkingExample-iOS/VimeoNetworkingExample-iOS.xcodeproj/xcshareddata/xcschemes/VimeoNetworkingExample-tvOS.xcscheme

Fixes new Xcode 10.2 warnings on redundant public modifiers, updated to recommended project settings

VIM-XXXX: Fixes new Xcode 10.2 warnings on redundant public modifiers, updated to recommended project settings

---

Sources/Shared/Scope.swift

Cherry picks from #330 - Thanks @DavidBemerguy for the contribution!

Adds email scope to Scope enum, order cases alphabetically

---

VimeoNetworking.xcodeproj/xcshareddata/xcschemes/VimeoNetworking-iOS.xcscheme
VimeoNetworking.xcodeproj/xcshareddata/xcschemes/VimeoNetworking-macOS.xcscheme
VimeoNetworking.xcodeproj/xcshareddata/xcschemes/VimeoNetworking-tvOS.xcscheme

Reverts vimeo/VimeoNetworking#341

Revert "Enables find implicit dependencies"
